export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const GET_ISSUES = 'GET_ISSUES';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAIL = 'GET_ISSUES_FAIL';

export const CREATE_ISSUE = 'CREATE_ISSUE';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const CREATE_ISSUE_FAIL = 'CREATE_ISSUE_FAIL';

export const OPEN_MODAL_DELETE_ISSUE = 'OPEN_MODAL_DELETE_ISSUE';
export const CLOSE_MODAL_DELETE_ISSUE = 'CLOSE_MODAL_DELETE_ISSUE';
export const DELETE_ISSUE_CONFIRM = 'DELETE_ISSUE_CONFIRM';

export const EDIT_ISSUE = 'EDIT_ISSUE';
export const EDIT_ISSUE_SUSSESS = 'EDIT_ISSUE_SUSSES';
export const EDIT_ISSUE_FAIL = 'EDIT_ISSUE_FAIL';
